<a href="https://colab.research.google.com/github/ManthanGarg-1234/AIML-CLASSWORK/blob/main/20_July_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

numbers = np.array([10, 20, 30, 40])
print("numbers: ",numbers)
print(numbers.ndim)
print(numbers.nbytes)
print(numbers.size)
print(numbers.dtype)
print(numbers.data)

numbers:  [10 20 30 40]
1
32
4
int64


In [ ]:

numbers = np.array( [[10, 20, 30, 40] , [50, 60, 70, 80]] )
print("numbers: ",numbers)
print(numbers.ndim)
print(numbers.nbytes)
print(numbers.size)
print(numbers.dtype)
print(numbers.data)

numbers:  [[10 20 30 40]
 [50 60 70 80]]
2
64
8
int64


In [ ]:

numbers1 = np.array( [[10, 20, 30, 40] , [50, 60, 70, 80]] )
numbers2 = np.array( [[10, 20, 30, 40] , [50, 60, 70, 80]] )
print("addition of both arrays: ",numbers1+numbers2)
print("subtraction of both arrays: ",numbers1-numbers2)
print("division of both arrays: ",numbers1/numbers2)
print("multiplication of both arrays: ",numbers1*numbers2)



addition of both arrays:  [[ 20  40  60  80]
 [100 120 140 160]]
subtraction of both arrays:  [[0 0 0 0]
 [0 0 0 0]]
division of both arrays:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
multiplication of both arrays:  [[ 100  400  900 1600]
 [2500 3600 4900 6400]]


In [ ]:

numbers1 =  ([10, 20, 30, 40])
numbers2 = ([50, 60, 70, 80])
print("addition of both arrays: ",numbers1+numbers2)
print("subtraction of both arrays: ",numbers1-numbers2)
print("division of both arrays: ",numbers1/numbers2)
print("multiplication of both arrays: ",numbers1*numbers2)


addition of both arrays:  [10, 20, 30, 40, 50, 60, 70, 80]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
Marks = [70, 80, 85, 90,95]
print(np.mean(Marks))
print(np.size(Marks))
print(np.median(Marks))
print(np.sum(Marks))
print(np.dot(Marks,2)) # 2 se all value multiply

84.0
5
85.0
420
[140 160 170 180 190]
