<a href="https://colab.research.google.com/github/ManthanGarg-1234/AIML-CLASSWORK/blob/main/20_July_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### Understanding NumPy Array Properties (1D)

This section demonstrates the various properties of a one-dimensional NumPy array, such as its dimensions, memory usage, total number of elements, data type, and memory address.

In [ ]:

numbers = np.array([10, 20, 30, 40])
print("numbers: ",numbers)
print(numbers.ndim)
print(numbers.nbytes)
print(numbers.size)
print(numbers.dtype)
print(numbers.data)

numbers:  [10 20 30 40]
1
32
4
int64


### Understanding NumPy Array Properties (2D)

This section extends the previous one by showing the same properties for a two-dimensional NumPy array, illustrating how these properties change with higher dimensions.

In [ ]:
# numbers: The array itself
# ndim: Number of dimensions
# nbytes: Total bytes consumed by the array elements
# size: Total number of elements
# dtype: Data type of the elements
# data: Python buffer object pointing to the start of the array's data

In [ ]:

numbers = np.array( [[10, 20, 30, 40] , [50, 60, 70, 80]] )
print("numbers: ",numbers)
print(numbers.ndim)
print(numbers.nbytes)
print(numbers.size)
print(numbers.dtype)
print(numbers.data)

numbers:  [[10 20 30 40]
 [50 60 70 80]]
2
64
8
int64


### Element-wise Arithmetic Operations with NumPy Arrays

NumPy arrays allow for efficient element-wise arithmetic operations. This section demonstrates addition, subtraction, division, and multiplication between two arrays of the same shape.

In [ ]:
# numbers: The 2D array
# ndim: Number of dimensions (should be 2 for a 2D array)
# nbytes: Total bytes consumed by the array elements
# size: Total number of elements (rows * columns)
# dtype: Data type of the elements
# data: Python buffer object pointing to the start of the array's data

In [ ]:

numbers1 = np.array( [[10, 20, 30, 40] , [50, 60, 70, 80]] )
numbers2 = np.array( [[10, 20, 30, 40] , [50, 60, 70, 80]] )
print("addition of both arrays: ",numbers1+numbers2)
print("subtraction of both arrays: ",numbers1-numbers2)
print("division of both arrays: ",numbers1/numbers2)
print("multiplication of both arrays: ",numbers1*numbers2)



addition of both arrays:  [[ 20  40  60  80]
 [100 120 140 160]]
subtraction of both arrays:  [[0 0 0 0]
 [0 0 0 0]]
division of both arrays:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
multiplication of both arrays:  [[ 100  400  900 1600]
 [2500 3600 4900 6400]]


### Arithmetic Operations on Python Lists vs. NumPy Arrays

This section highlights the difference in behavior when performing arithmetic operations on standard Python lists compared to NumPy arrays. Python lists concatenate with `+` and do not support element-wise `-`, `/`, or `*` for numerical operations directly. To perform element-wise arithmetic, lists must first be converted into NumPy arrays.

In [ ]:
# numbers1 and numbers2 are NumPy arrays.
# When arithmetic operations (+, -, /, *) are performed on NumPy arrays, they are applied element-wise.
# For example, numbers1 + numbers2 adds corresponding elements from both arrays.

In [ ]:

numbers1 =  ([10, 20, 30, 40])
numbers2 = ([50, 60, 70, 80])
print("addition of both arrays: ",numbers1+numbers2)
print("subtraction of both arrays: ",numbers1-numbers2)
print("division of both arrays: ",numbers1/numbers2)
print("multiplication of both arrays: ",numbers1*numbers2)


addition of both arrays:  [10, 20, 30, 40, 50, 60, 70, 80]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

### Statistical Analysis with NumPy

This section demonstrates how to use NumPy functions to calculate various statistics (mean, size, median, standard deviation, maximum, sum, and dot product) on a list of numerical data.

In [ ]:
# Original lists that caused TypeError when attempting element-wise subtraction, division, and multiplication.
# Python lists concatenate with '+', but do not support other element-wise arithmetic operations.
# To perform element-wise operations, convert them to NumPy arrays.

In [33]:
Marks = [70, 80, 85, 90,95]
print(np.mean(Marks))
print(np.size(Marks))
print(np.median(Marks))
print(np.std(Marks))
print(np.max(Marks))
print(np.sum(Marks))
print(np.dot(Marks,2)) # 2 se all value multiply

84.0
5
85.0
8.602325267042627
95
420
[140 160 170 180 190]


In [ ]:
# Marks: A Python list of numerical data (e.g., student marks).
# np.mean(): Calculates the average of the elements.
# np.size(): Returns the number of elements in the array/list.
# np.median(): Calculates the median of the elements.
# np.std(): Calculates the standard deviation, a measure of data dispersion.
# np.max(): Finds the maximum value in the elements.
# np.sum(): Calculates the sum of all elements.
# np.dot(Marks, 2): In this context, for a 1D array/list and a scalar, it performs scalar multiplication on each element.
